name: 'Deploy to AppZung CodePush'
description: 'Deploy React Native updates to AppZung CodePush for over-the-air updates'
author: 'AppZung'

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  api-key:
    description: 'AppZung API key for authentication. An API key that has access to this project.'
    required: true

  release-channel:
    description: 'The release channel ID to deploy to (e.g., "myReleaseChannelDescription/c95d7950-228c-4f47-8abb-4e275050ca8e")'
    required: true

  mandatory:
    description: 'Specifies whether this release should be considered mandatory'
    required: false
    default: 'false'

  disabled:
    description: 'Specifies whether this release should be disabled (not immediately available, can be enabled later)'
    required: false
    default: 'false'

  rollout:
    description: 'Percentage points of users this release should be available to (e.g., 95 for 95%)'
    required: false
    default: ''

  target-binary-version:
    description: 'Semver version that specifies the binary app version this release is compatible with. If left unspecified, it will try to find the correct version.'
    required: false
    default: ''

  private-key:
    description: 'Private key for code signing. Can be either a file path (relative to project root) or the actual private key content.'
    required: false
    default: ''

  description-from-git:
    description: 'Use the current git commit message as the release description'
    required: false
    default: 'false'

  extra-flags:
    description: 'Any additional command line flags you want to pass to the deploy command. Example: "--disable-duplicate-release-error --use-hermes"'
    required: false
    default: ''

  working-directory:
    description: 'Directory from which to run the deploy command, useful for monorepos or projects with non-standard structure'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Deploy React Native update to AppZung CodePush
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        INPUT_API_KEY: ${{ inputs.api-key }}
        INPUT_RELEASE_CHANNEL: ${{ inputs.release-channel }}
        INPUT_MANDATORY: ${{ inputs.mandatory }}
        INPUT_DISABLED: ${{ inputs.disabled }}
        INPUT_ROLLOUT: ${{ inputs.rollout }}
        INPUT_TARGET_BINARY_VERSION: ${{ inputs.target-binary-version }}
        INPUT_PRIVATE_KEY: ${{ inputs.private-key }}
        INPUT_DESCRIPTION_FROM_GIT: ${{ inputs.description-from-git }}
        INPUT_EXTRA_FLAGS: ${{ inputs.extra-flags }}
      run: ${{ github.action_path }}/deploy.sh
